### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v42-toucans-team-02#12]
**__Feature Description__**
Prepare for your Voyage by becoming familiar with the Chingu practices & procedures.

**__Major User Stories/tasks__**
- [x] Getting Started: 🚀 Understand the Voyage Process #11 
- [x] Getting Started: 📜 Review the Chingu Agile Methodology #2
- [x] Getting Started: 🤔 Start thinking about project ideas & the technical stack #3 
- [x] Getting Started: 🙋 Do you have questions about Chingu or the Voyage process? #4 

**__Additional Considerations__**
N/a

**Comment by GillianTrethewey** [comment]
Colour mockup was created instead of wireframe. 
Project has been laid out in scope by Chingu Admin, so decisions have been made in general. Later on in the Sprints, we may add some features beyond this if time permits.
