### ISSUE TITLE
Overall Homepage Description

### ISSUE THREAD

**Issue by GillianTrethewey** [chingu-voyages/v42-toucans-team-02#14]
**__Feature Description__**
Build the homepage with these sections:
1. Navigation
2. Hero
3. Search for Joke
4. Footer with team credits

**__Major User Stories/tasks__**
- [x] The navbar will display the page categories
- [x] When clicked will navigate user to that category on the page
- [x] The hero area will outline the purpose of the page
- [x] The search area displays two buttons for different search methods for jokes
- [x] The search are includes an area for the joke to be displayed
- [x] The footer area will have information on the project
- [x] The footer area will have information on the team

**__Additional Considerations__**
Initial Design:
![chuck-norris-time](https://user-images.githubusercontent.com/7611178/211621036-9a7d146c-22cd-4d68-b47d-959ed9da05e1.png)

**Comment by LyleT** [comment]
Change/correct spelling of contributor's last name - Lyle TRETHEWEY & Gillian TRETHEWEY to be included in the footer.

**Comment by GillianTrethewey** [comment]
Design colours changed for accessibility requirements (contrast), image changed for Creative Commons licensing. Initial design completed, to be tweaked further in Sprint 3.
